Add vcpkg feature support for fuller range of configure options
You can now specify options to enable any of these:
- decoders
- encoders
- hwaccels
- demuxers
- muxers
- parsers
- protocols
- bsfs
- indevs
- outdevs
- filters

I got the full list by running the following with the configure script for ffmpeg (ex. ./configure --list-decoders):
  --list-decoders          show all available decoders
  --list-encoders          show all available encoders
  --list-hwaccels          show all available hardware accelerators
  --list-demuxers          show all available demuxers
  --list-muxers            show all available muxers
  --list-parsers           show all available parsers
  --list-protocols         show all available protocols
  --list-bsfs              show all available bitstream filters
  --list-indevs            show all available input devices
  --list-outdevs           show all available output devices
  --list-filters           show all available filters

I wanted to just have no description with the vcpkg features, to be concise.  I found, however, that description IS required.  It can be an empty string, but it must be there.  If it is not, it returns errors like this:

If you do not specify a description for a feature, you will get errors like this: error: $.features.decoder-aac (a feature): missing required field 'description' (a string or array of strings)

Also, sadly, there appears to be a 2015 feature limit in vcpkg.json (found by trial and error).  If you specify over 2015, it fails out with a message that looks like this the one below.  There are no error logs in this case, so it is not obvious what the problem is.  I have therefore not included all of the filters, to cut this feature set down, so we will have to add vcpkg features for specific filters we want to use in the future, since I cannot add them all, as it would put us over that 2015 cap.

--- Error you get when you try to specify over 2015 features in vcpkg.json ---
Installing 1/1 ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,swresample,swscale,tsc-base,tsc-desktop-base,tsc-desktop-win]:x64-windows-dynamic-release@7.1.1#1...
Building ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,swresample,swscale,tsc-base,tsc-desktop-base,tsc-desktop-win]:x64-windows-dynamic-release@7.1.1#1...
C:\code\ThirdParty-Packages-vcpkg\custom-triplets\x64-windows-dynamic-release.cmake: info: loaded overlay triplet from here
C:\code\ThirdParty-Packages-vcpkg\custom-ports\ffmpeg: info: installing overlay port from here
error: building ffmpeg:x64-windows-dynamic-release failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle ffmpeg:x64-windows-dynamic-release: 3.45 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+ffmpeg
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[ffmpeg]+Build+error+on+x64-windows-dynamic-release&body=Copy%20issue%20body%20from%20C%3A%2Fcode%2FThirdParty-Packages-vcpkg%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
You can also submit an issue by running (GitHub CLI must be installed):
  "C:\Program Files\GitHub CLI\gh.exe" issue create -R microsoft/vcpkg --title "[ffmpeg] Build failure on x64-windows-dynamic-release" --body-file C:/code/ThirdParty-Packages-vcpkg/vcpkg/installed/vcpkg/issue_body.md
Error: The last command returned an exit code of 1.

Fix ffmpeg package configs broken by last commit