Prevent checking out tags unnecessarily (can cause issues on Mac)
This should fix errors like this:

error: cannot lock ref 'refs/tags/ffmpeg-wasm-base-7.1--vp9': Unable to create '/Users/runner/work/1/s/.git/refs/tags/ffmpeg-wasm-base-7.1--vp9.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.